base_url = "https://thepatrickfisher.com"
title = "Patrick Fisher"
description = "Patrick Fisher — SRE, DevOps, Systems Engineer, Mad Scientist."
author = "hello@thepatrickfisher.com (Patrick Fisher)"
generate_feeds = true
feed_filenames = ["rss.xml"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
